apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumananand-app-deployment
spec: # Defines the Deployment Behaviour
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: #Define Pod Behaviour
      containers:
      - name: min-app
        image: muralisocial123/flower-app:1.0
        ports:
          - containerPort: 3015
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"
