apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumananand-app-deployment
spec: # Defines the Deployment Behaviour
  replicas: 3
  selector:
    matchLabels:
      app: kumar
  template:
    metadata:
      labels:
        app: kumar
    spec: #Define Pod Behaviour
      containers:
      - name: min-app
        image: muralisocial123/flower-app:1.0
        ports:
          - containerPort: 3015
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"
---
# Writing Service.yaml to expose the application
apiVersion: v1
kind: Service
metadata:
  name: kumar
spec:
  selector:
    app: kumar
  ports:
  - port: 3016 #Service Port
    targetPort: 3015 # Container Port
  type: LoadBalancer